import type { ThresholdItem } from "./types";

export const icons: Record<string, string> = {
  grid: '<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect></svg>',
  lab: '<svg viewBox="0 0 24 24"><path d="M10 2v7.5L5.5 18a3 3 0 0 0 2.6 4h7.8a3 3 0 0 0 2.6-4L14 9.5V2"></path><path d="M8 2h8"></path><path d="M7 16h10"></path></svg>',
  sliders: '<svg viewBox="0 0 24 24"><path d="M4 7h7"></path><path d="M15 7h5"></path><path d="M13 5v4"></path><path d="M4 12h3"></path><path d="M11 12h9"></path><path d="M9 10v4"></path><path d="M4 17h10"></path><path d="M18 17h2"></path><path d="M16 15v4"></path></svg>',
  pin: '<svg viewBox="0 0 24 24"><path d="M12 21s7-5.4 7-12a7 7 0 1 0-14 0c0 6.6 7 12 7 12z"></path><circle cx="12" cy="9" r="2.5"></circle></svg>',
  chart: '<svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="2"></rect><path d="M8 17v-5"></path><path d="M12 17V8"></path><path d="M16 17v-3"></path></svg>',
  upload: '<svg viewBox="0 0 24 24"><path d="M12 16V4"></path><path d="m7 9 5-5 5 5"></path><path d="M5 20h14"></path></svg>',
  info: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M12 11v5"></path><path d="M12 8h.01"></path></svg>',
  chevron: '<svg viewBox="0 0 24 24"><path d="m6 15 6-6 6 6"></path></svg>',
  bell: '<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>',
  more: '<svg viewBox="0 0 24 24"><circle cx="12" cy="5" r="1.5"></circle><circle cx="12" cy="12" r="1.5"></circle><circle cx="12" cy="19" r="1.5"></circle></svg>',
  collapseLeft: '<svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"></path></svg>',
};

export const thresholds: ThresholdItem[] = [
  { key: "avg_age_years", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "年龄", en: "Age" }, group: { zh: "基线人口学", en: "Baseline Demographics" }, min: 0, max: 90, step: 1, value: 50, decimals: 1, enabled: true },
  { key: "male_rate", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "受试者性别比例", en: "Subject Sex Ratio" }, group: { zh: "基线人口学", en: "Baseline Demographics" }, min: 0, max: 1, step: 0.01, value: 0.6, decimals: 2, enabled: true },
  { key: "baseline_hba1c_avg", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "基线HbA1c平均值", en: "Baseline HbA1c Average" }, group: { zh: "基线疗效特征", en: "Baseline Efficacy" }, min: 0, max: 14, step: 0.1, value: 8.5, decimals: 1, enabled: true },
  { key: "baseline_bmi_avg", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "基线BMI平均值", en: "Baseline BMI Average" }, group: { zh: "基线BMI", en: "Baseline BMI" }, min: 0, max: 45, step: 0.1, value: 29, decimals: 1, enabled: true },
  { key: "bmi_under_24_rate", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "BMI<24比例", en: "BMI <24 Rate" }, group: { zh: "基线BMI", en: "Baseline BMI" }, min: 0, max: 1, step: 0.01, value: 0.03, decimals: 2, enabled: true },
  { key: "bmi_30_35_rate", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "BMI 30-35比例", en: "BMI 30-35 Rate" }, group: { zh: "基线BMI", en: "Baseline BMI" }, min: 0, max: 1, step: 0.01, value: 0.15, decimals: 2, enabled: true },
  { key: "bmi_over_35_count", department: "MM", department_label: { zh: "MM", en: "MM" }, label: { zh: "BMI>35病例数", en: "BMI >35 Count" }, group: { zh: "基线BMI", en: "Baseline BMI" }, min: 0, max: 20, step: 1, value: 0, decimals: 0, enabled: true },
  { key: "hba1c_missing_rate", department: "ST", department_label: { zh: "ST", en: "ST" }, label: { zh: "HbA1c数据缺失受试者比例", en: "HbA1c Missing Subject Rate" }, group: { zh: "疗效数据完整性", en: "Efficacy Completeness" }, min: 0, max: 1, step: 0.01, value: 0.15, decimals: 2, enabled: true },
  { key: "weight_missing_rate", department: "ST", department_label: { zh: "ST", en: "ST" }, label: { zh: "体重数据缺失受试者比例", en: "Weight Missing Subject Rate" }, group: { zh: "疗效数据完整性", en: "Efficacy Completeness" }, min: 0, max: 1, step: 0.01, value: 0.15, decimals: 2, enabled: true },
  { key: "concomitant_event_rate", department: "ST", department_label: { zh: "ST", en: "ST" }, label: { zh: "伴发事件受试者比例", en: "Concomitant Event Subject Rate" }, group: { zh: "关键事件", en: "Critical Events" }, min: 0, max: 1, step: 0.01, value: 0.2, decimals: 2, enabled: true },
  { key: "early_termination_rate", department: "PM", department_label: { zh: "PM", en: "PM" }, label: { zh: "W44前提前退出受试者比例", en: "Pre-W44 Early Termination Rate" }, group: { zh: "受试者留存", en: "Subject Retention" }, min: 0, max: 1, step: 0.01, value: 0.1, decimals: 2, enabled: true },
  { key: "pregnancy_rate", department: "PM", department_label: { zh: "PM", en: "PM" }, label: { zh: "妊娠受试者比例", en: "Pregnancy Subject Rate" }, group: { zh: "安全性事件", en: "Safety Events" }, min: 0, max: 0.2, step: 0.01, value: 0.02, decimals: 2, enabled: true },
  { key: "edc_visit_entry_delay_days", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "EDC访视录入延迟天数", en: "EDC Visit Entry Delay Days" }, group: { zh: "录入及时性", en: "Entry Timeliness" }, min: 0, max: 90, step: 1, value: 30, decimals: 0, enabled: true },
  { key: "page_missing_days_all", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "页面缺失天数（全部）", en: "Page Missing Days (All)" }, group: { zh: "页面质量", en: "Page Quality" }, min: 1, max: 90, step: 1, value: 30, decimals: 0, enabled: true },
  { key: "page_missing_days_without_lab", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "页面缺失天数（不含对接LAB）", en: "Page Missing Days (Excl. Linked Lab)" }, group: { zh: "页面质量", en: "Page Quality" }, min: 1, max: 90, step: 1, value: 30, decimals: 0, enabled: true },
  { key: "page_sdv_pending_rate", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "未SDV（页面）", en: "Un-SDV (Page)" }, group: { zh: "页面质量", en: "Page Quality" }, min: 1, max: 90, step: 1, value: 42, decimals: 0, enabled: true },
  { key: "logline_sdv_pending_rate", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "未SDV（logline）", en: "Un-SDV (Logline)" }, group: { zh: "页面质量", en: "Page Quality" }, min: 1, max: 90, step: 1, value: 42, decimals: 0, enabled: true },
  { key: "avg_open_query_age_days", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "未关闭质疑天数", en: "Open Query Days" }, group: { zh: "Query账龄", en: "Query Age" }, min: 1, max: 90, step: 1, value: 30, decimals: 0, enabled: true },
  { key: "manual_query_reissue_rate", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "人工质疑重发率", en: "Manual Query Reissue Rate" }, group: { zh: "Query返工", en: "Query Rework" }, min: 0.01, max: 1, step: 0.01, value: 0.1, decimals: 2, enabled: true },
  { key: "data_consistency_issue_days", department: "DM", department_label: { zh: "DM", en: "DM" }, label: { zh: "数据一致性问题未解决天数", en: "Data Consistency Issue Days" }, group: { zh: "数据一致性", en: "Data Consistency" }, min: 1, max: 90, step: 1, value: 30, decimals: 0, enabled: true },
];

export const scoreColumnsByMetric: Record<string, string[]> = {
  avg_age_years: ["MM基线特征评分"],
  male_rate: ["MM基线特征评分"],
  baseline_hba1c_avg: ["MM基线特征评分"],
  baseline_bmi_avg: ["MM基线特征评分"],
  bmi_under_24_rate: ["MM基线特征评分"],
  bmi_30_35_rate: ["MM基线特征评分"],
  bmi_over_35_count: ["MM基线特征评分"],
  edc_visit_entry_delay_days: ["EDC及时性评分"],
  page_missing_days_all: ["页面质量评分"],
  page_missing_days_without_lab: ["页面质量评分"],
  page_sdv_pending_rate: ["页面质量评分"],
  logline_sdv_pending_rate: ["页面质量评分"],
  manual_query_reissue_rate: ["Query返工评分"],
  avg_open_query_age_days: ["Query周期评分"],
  hba1c_missing_rate: ["疗效数据完整性评分"],
  weight_missing_rate: ["疗效数据完整性评分"],
  concomitant_event_rate: ["安全性/事件评分"],
  early_termination_rate: ["受试者留存评分"],
  pregnancy_rate: ["安全性/事件评分"],
  data_consistency_issue_days: ["数据一致性评分"],
};
